language: generic
sudo: true

services:
  - docker

env:
  matrix:
    - TAG=stretch
    - TAG=buster
    # TODO: Add bullseye support, after resolving this error:
    # E: The repository 'http://security-cdn.debian.org/debian-security bullseye/updates Release' does not have a Release file.
    # - TAG=bullseye

script:
  - make build
  - make test

before_deploy:
  - export DOCKER_CONFIG="${HOME}/.docker"
  - mkdir -p "$DOCKER_CONFIG"
  - openssl aes-256-cbc -K $encrypted_a8d6dc0564c6_key -iv $encrypted_a8d6dc0564c6_iv -in .docker/config.json.enc -out "${DOCKER_CONFIG}/config.json" -d

deploy:
  provider: script
  skip_cleanup: true
  script: make push
  on:
    branch: master
