FROM debian:<%= ENV.fetch 'TAG' %>
MAINTAINER Frank Macreery <frank@macreery.com>

# Add custom files
# TODO: Figure out why `ADD files /` creates a huge layer
ADD files/root/bashrc /root/.bashrc
ADD files/usr/bin/apt-install /usr/bin/apt-install

# Install wget
RUN apt-install wget ca-certificates tzdata

# Install latest security updates now, and on build
RUN grep security /etc/apt/sources.list > /tmp/security.list
RUN apt-get -o Dir::Etc::SourceList=/tmp/security.list update \
 && apt-get -o Dir::Etc::SourceList=/tmp/security.list upgrade -y \
 && rm -rf /var/lib/apt/lists/*
ONBUILD RUN apt-get -o Dir::Etc::SourceList=/tmp/security.list update \
         && apt-get -o Dir::Etc::SourceList=/tmp/security.list upgrade -y \
         && rm -rf /var/lib/apt/lists/*

# Install Bats
RUN wget https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz && \
    tar xzf v0.4.0.tar.gz && cd bats-0.4.0 && ./install.sh /usr/local && \
    cd .. && rm -rf v0.4.0.tar.gz bats-0.4.0

# Integration tests
ADD test /tmp/test
RUN bats /tmp/test

CMD /bin/bash
