name: Release

on:
  push:
    branches:
      - "master"

jobs:
  build:
    strategy:
      matrix:
        version: ['stretch','buster','bullseye','bookworm']
    runs-on: ubuntu-latest
    env:
      REPOSITORY: debian

    steps:

    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Login to Quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
  
    - name: Docker metadata
      id: metadata
      uses: docker/metadata-action@v4
      with:
        images: |
          aptible/${{ env.REPOSITORY }}
          quay.io/aptible/${{ env.REPOSITORY }}
        flavor: |
          latest=false
        tags: |
          type=schedule
          type=ref,event=branch,suffix=${{ format('-{0}', matrix.version) }}
          type=ref,event=tag,suffix=${{ format('-{0}', matrix.version) }}
          type=ref,event=pr,suffix=${{ format('-{0}', matrix.version) }}

    - name: Build and Push
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v4
      with:
        context: .
        build-args: TAG=${{ steps.metadata.outputs.tags }}
        file: ./Dockerfile
        push: true
        target: ${{ steps.metadata.outputs.images }}
        tags: ${{ steps.metadata.outputs.tags }}
