name: Release

on:
  push:
    branches:
      - "master"

jobs:
  build:
    strategy:
      matrix:
        debian: ['stretch','buster','bullseye','bookworm']
    runs-on: ubuntu-latest
    env:
      IMG_NAME: aptible/debian
      REGISTRY: quay.io
      REPOSITORY: aptible/debian
      PUSH_REGISTRIES: $(REGISTRY) docker.io
      TAG: ${{ matrix.debian }}

    steps:

    - uses: actions/checkout@v4
    
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    -
      name: Login to Quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker metadata
      id: metadata
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.IMG_NAME }}
        tags:  ${{ matrix.debian }}

    - name: Make Build
      run: make build

    - name: Run Tests
      run: make test

    - name: Make push
      if: github.event_name != 'pull_request'
      run: make push
