name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
      branches: 
      - "*"

jobs:
  build:
    strategy:
      matrix:
        debian: ['stretch','buster','bullseye','bookworm']
    runs-on: ubuntu-latest
    env:
      IMG_NAME: aptible/debian

    steps:

    - uses: actions/checkout@v4
    
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker metadata
      id: metadata
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.IMG_NAME }}
        tags:  ${{ matrix.debian }}

    - name: Make Build
      run: make build

    - name: Run Tests
      run: make test